trigger:
  branches:
    include: [main]
  paths:
    include:
      - src/terraform/stages/03-cluster
      - src/terraform/modules/
      - src/pipelines/

variables:
  - group: 'TF_LIBRARY'
  - name: stage
    value: 03-cluster
  - name: tf_state_rg
    value: "tfstates" # name of the resource group to create/use for the terraform state file
  - name: tf_state_sa_name
    value: "tfstateblobs" # name of of the storage account to create/use for the terraform state file
  - name: TF_VAR_environment
    value: dev
  - name: IS_NOT_PR
    value: "${{ eq(lower(startsWith(variables['Build.SourceBranch'], 'refs/pull/')), 'false') }}"
  - name: EXTRA_OPTS
    value: "-var-file=../vars/common.tfvars -var-file=../vars/${{ variables.TF_VAR_environment }}.tfvars"


stages:
  - template: templates/stages-terraform-deploy.yml
    parameters:
      EXTRA_OPTS: ${{ variables.EXTRA_OPTS }}
      WORKDIR: src/terraform/stages/${{ variables.stage }}
      tf_state_rg: ${{ variables.tf_state_rg }}
      tf_state_sa_name: ${{ variables.tf_state_sa_name }}
      tf_state_key: ${{ variables.stage }}
      IS_NOT_PR: ${{ variables['IS_NOT_PR'] }}
      ARM_SERVICE_CONNECTION: $(ARM_SERVICE_CONNECTION)
      ARM_SERVICE_CONNECTION_NAME: $(ARM_SERVICE_CONNECTION_NAME)
