apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: cluster-config
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: infra-apps-flux-config
  path: ./src/gitops/apps/
  prune: true
  validation: client
