apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: cluster-config
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: infra-apps-flux-config
  path: ./src/gitops/infra/
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: nginx-ingress-ingress-nginx-controller
      namespace: ingress-nginx
